
import { Project } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Neon Strike RPG',
    description: 'Sumérgete en un mundo ciberpunk donde tus decisiones alteran el destino de la humanidad. Combates tácticos y una narrativa ramificada te esperan en esta joya indie.',
    category: 'JUEGO',
    author: 'CyberNaut Studio',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    donationGoal: 5000,
    currentDonation: 3420,
    downloadCount: 1250,
    likes: 420,
    repositoryUrl: 'https://github.com/sparkz/neon-strike',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'ZenFocus Pro',
    description: 'La herramienta definitiva para el trabajo profundo. Bloquea distracciones, gestiona tus pomodoros y sincroniza tus notas en todos tus dispositivos con cifrado de extremo a extremo.',
    category: 'APP',
    author: 'MindfulDev',
    image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&q=80&w=800',
    donationGoal: 2000,
    currentDonation: 1100,
    downloadCount: 5600,
    likes: 890,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Arquitectura del Mañana',
    description: 'Un viaje visual y teórico por las ciudades del futuro. Este libro interactivo explora cómo la sostenibilidad y la tecnología cambiarán nuestro hogar.',
    category: 'LIBRO',
    author: 'ArchViz Group',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
    donationGoal: 800,
    currentDonation: 650,
    downloadCount: 430,
    likes: 125,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Pixel Odyssey',
    description: 'Un plataformero retro que desafía la gravedad. Con más de 100 niveles hechos a mano, es una carta de amor a la era de los 16 bits.',
    category: 'JUEGO',
    author: 'RetroPixels',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800',
    donationGoal: 3000,
    currentDonation: 2800,
    downloadCount: 8900,
    likes: 2100,
    createdAt: new Date().toISOString(),
  },
];
